#### Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([3,4,5,6,7])

In [4]:
arr

array([3, 4, 5, 6, 7])

In [5]:
arr.ndim

1

In [6]:
arr2 = np.array([[2,3,4],[2,3,6]])

In [7]:
arr2

array([[2, 3, 4],
       [2, 3, 6]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 3)

#### Array indexing

In [12]:
arr

array([3, 4, 5, 6, 7])

In [13]:
arr[0]

3

In [14]:
arr[2]

5

In [15]:
arr[-1]

7

In [16]:
arr2

array([[2, 3, 4],
       [2, 3, 6]])

In [17]:
arr2[0,0]

2

In [19]:
arr2[1,2]

6

In [20]:
arr_ = np.array([[2,3,4,5,6], [2,3,4,2,4], [2,3,4,2,4]])

In [21]:
arr_[

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 2, 4],
       [2, 3, 4, 2, 4]])

In [22]:
arr_.shape

(3, 5)

In [25]:
arr_[-2,-2]

2

#### Array Slicing

In [26]:
arr

array([3, 4, 5, 6, 7])

In [27]:
arr[1:4]

array([4, 5, 6])

In [28]:
arr2

array([[2, 3, 4],
       [2, 3, 6]])

In [30]:
arr2[0:2,0:2]

array([[2, 3],
       [2, 3]])

In [31]:
arr2[0, 1:]

array([3, 4])

In [36]:
arr__ = arr2[0:2,1:2]

In [37]:
arr__.shape

(2, 1)

In [38]:
arr__

array([[3],
       [3]])

#### Array Reshaping

In [44]:
number = np.array([7,3,4,5,6,7,8,2])

In [40]:
number.ndim

1

In [41]:
number.shape

(8,)

In [50]:
num = number.reshape(4,2)

In [47]:
num

array([[7, 3],
       [4, 5],
       [6, 7],
       [8, 2]])

In [48]:
num.shape

(4, 2)

In [51]:
## Array flattening

num

array([[7, 3],
       [4, 5],
       [6, 7],
       [8, 2]])

In [52]:
num.reshape(-1)

array([7, 3, 4, 5, 6, 7, 8, 2])

In [53]:
arr2

array([[2, 3, 4],
       [2, 3, 6]])

In [54]:
arr2.reshape(-1)

array([2, 3, 4, 2, 3, 6])

In [61]:
names = numpy.array(["Mac", "Ben", "Taiwo", 9])

In [62]:
names.dtype

dtype('<U11')

In [63]:
names

array(['Mac', 'Ben', 'Taiwo', '9'], dtype='<U11')

In [59]:
num

array([[7, 3],
       [4, 5],
       [6, 7],
       [8, 2]])

In [60]:
num.dtype

dtype('int32')

In [74]:
number = np.array(['hsj','yeu'], dtype='S')

In [75]:
number

array([b'hsj', b'yeu'], dtype='|S3')

### Statistical Methods

In [76]:
arr

array([3, 4, 5, 6, 7])

In [77]:
arr.mean()

5.0

In [79]:
np.median(arr)

5.0

In [80]:
np.mean(arr)

5.0

In [81]:
np.std(arr)

1.4142135623730951

In [82]:
np.var(arr)

2.0

In [85]:
scores = np.array([90,20,40,50,20,100])

scores.mean()

53.333333333333336

In [88]:
np.std(scores)

31.446603773522014

#### Statistics

--  Summary Stats (Descriptive Stats)
   -- Measure of Central Tendency : Mean, median , mode
   -- Measure of variations : S.D, variance, Range

-- Probability and Distributions

-- Central Limit theroem 

-- Hypothesis Testing

##### Pandas

--  `Series`

-- `DataFrame`

#### Series

A pandas series is like a column in a table

In [1]:
import pandas as pd

In [2]:
ages = pd.Series([4,5,6,7])

In [3]:
ages

0    4
1    5
2    6
3    7
dtype: int64

In [4]:
names = pd.Series(['Ayobami', 'Vin', 'Blessing', 'Segun'], index = [1,2,3,4])

In [5]:
names

1     Ayobami
2         Vin
3    Blessing
4       Segun
dtype: object

In [6]:
names.dtype

dtype('O')

In [7]:
names[3]

'Blessing'

In [8]:
names[2]

'Vin'

In [11]:
names[1:4]

2         Vin
3    Blessing
4       Segun
dtype: object

#### DataFrame

A pandas DataFrame is a 2 dim data structure with rows and columns

In [12]:
students = {
    'Ayobami' : [90, 98, 89],
    'Blessing' : [98, 100, 90],
    'Vincent' : [90, 100, 98]
}

In [13]:
students

{'Ayobami': [90, 98, 89], 'Blessing': [98, 100, 90], 'Vincent': [90, 100, 98]}

In [14]:
df =  pd.DataFrame(students) 

In [15]:
df

Ayobami  Blessing  Vincent
0       90        98       90
1       98       100      100
2       89        90       98

In [16]:
df2 = pd.DataFrame(students, index=['a', 'b', 'c'])

In [17]:
df2

Ayobami  Blessing  Vincent
a       90        98       90
b       98       100      100
c       89        90       98

In [18]:
sports = [
    ['Football', 'Tennis', 'Swimming'],
    [11, 2, 6]
]

In [19]:
sports[0]

['Football', 'Tennis', 'Swimming']

In [20]:
sports[1]

[11, 2, 6]

In [21]:
sports[0][0]

'Football'

In [26]:
df3 = pd.DataFrame(sports, columns = ['Football', 'Tennis', 'Swimming'], index =[1,2])

In [27]:
df3

Football  Tennis  Swimming
1  Football  Tennis  Swimming
2        11       2         6

In [28]:
df

Ayobami  Blessing  Vincent
0       90        98       90
1       98       100      100
2       89        90       98

In [29]:
df.loc[0]

Ayobami     90
Blessing    98
Vincent     90
Name: 0, dtype: int64

In [30]:
df.loc[1]

Ayobami      98
Blessing    100
Vincent     100
Name: 1, dtype: int64

In [31]:
df.loc[2]

Ayobami     89
Blessing    90
Vincent     98
Name: 2, dtype: int64

In [32]:
df2

Ayobami  Blessing  Vincent
a       90        98       90
b       98       100      100
c       89        90       98

In [33]:
df2.loc['a']  # by label

Ayobami     90
Blessing    98
Vincent     90
Name: a, dtype: int64

In [37]:
df2.iloc[0] # by index

Ayobami     90
Blessing    98
Vincent     90
Name: a, dtype: int64

In [35]:
df2.loc['c']

Ayobami     89
Blessing    90
Vincent     98
Name: c, dtype: int64

In [36]:
df2.iloc[2]

Ayobami     89
Blessing    90
Vincent     98
Name: c, dtype: int64

In [38]:
df2.loc[:, 'Ayobami']

a    90
b    98
c    89
Name: Ayobami, dtype: int64

In [39]:
df2.loc[:,'Vincent']

a     90
b    100
c     98
Name: Vincent, dtype: int64

In [44]:
df2.loc['a':'b', 'Vincent']

a     90
b    100
Name: Vincent, dtype: int64

In [45]:
df2.iloc[:, 0]

a    90
b    98
c    89
Name: Ayobami, dtype: int64

In [46]:
df2.iloc[:,1]

a     98
b    100
c     90
Name: Blessing, dtype: int64

In [47]:
df2.loc[:, ['Ayobami', 'Blessing']]

Ayobami  Blessing
a       90        98
b       98       100
c       89        90

In [48]:
df2.loc[:,'Ayobami':'Blessing']

Ayobami  Blessing
a       90        98
b       98       100
c       89        90

In [51]:
df2.iloc[:, :2]

Ayobami  Blessing
a       90        98
b       98       100
c       89        90

In [52]:
df2

Ayobami  Blessing  Vincent
a       90        98       90
b       98       100      100
c       89        90       98

##### Reading in a csv file into a pandas dataFrame

In [56]:
ss_df = pd.read_csv('Superstore dataset.csv')

In [58]:
ss_df

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class   
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class   
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class   
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class   
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class   
...      ...             ...         ...         ...             ...   
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class   
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson   
1       CG-12520       Claire Gute   Consumer  United States        Henderson   
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles   
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
...          ...               ...        ...            ...              ...   
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago   
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo   
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo   
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo   
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo   

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture   
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture   
2     California      90036.0     West  OFF-LA-10000240  Office Supplies   
3        Florida      33311.0    South  FUR-TA-10000577        Furniture   
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies   
...          ...          ...      ...              ...              ...   
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies   
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies   
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology   
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology   
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology   

     Sub-Category                                       Product Name     Sales  
0       Bookcases                  Bush Somerset Collection Bookcase  261.9600  
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400  
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200  
3          Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775  
4         Storage                     Eldon Fold 'N Roll Cart System   22.3680  
...           ...                                                ...       ...  
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980  
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.3680  
9797       Phones                                        GE 30524EE4  235.1880  
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.3760  
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.3840  

[9800 rows x 18 columns]

#### Data Exploration

In [60]:
ss_df.head(6)

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520   
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520   
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045   
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335   
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335   
5       6  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710   

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky   
1      Claire Gute   Consumer  United States        Henderson    Kentucky   
2  Darrin Van Huff  Corporate  United States      Los Angeles  California   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida   
5  Brosina Hoffman   Consumer  United States      Los Angeles  California   

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases   
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs   
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels   
3      33311.0  South  FUR-TA-10000577        Furniture       Tables   
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage   
5      90032.0   West  FUR-FU-10001487        Furniture  Furnishings   

                                        Product Name     Sales  
0                  Bush Somerset Collection Bookcase  261.9600  
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400  
2  Self-Adhesive Address Labels for Typewriters b...   14.6200  
3      Bretford CR4500 Series Slim Rectangular Table  957.5775  
4                     Eldon Fold 'N Roll Cart System   22.3680  
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600

In [61]:
ss_df.tail()

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class   
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   

     Customer ID     Customer Name    Segment        Country     City  \
9795    SH-19975     Sally Hughsby  Corporate  United States  Chicago   
9796    CS-12490  Cindy Schnelling  Corporate  United States   Toledo   
9797    CS-12490  Cindy Schnelling  Corporate  United States   Toledo   
9798    CS-12490  Cindy Schnelling  Corporate  United States   Toledo   
9799    CS-12490  Cindy Schnelling  Corporate  United States   Toledo   

         State  Postal Code   Region       Product ID         Category  \
9795  Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies   
9796      Ohio      43615.0     East  OFF-AR-10001374  Office Supplies   
9797      Ohio      43615.0     East  TEC-PH-10004977       Technology   
9798      Ohio      43615.0     East  TEC-PH-10000912       Technology   
9799      Ohio      43615.0     East  TEC-AC-10000487       Technology   

     Sub-Category                                       Product Name    Sales  
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.798  
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.368  
9797       Phones                                        GE 30524EE4  235.188  
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.376  
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.384

In [63]:
ss_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9800 non-null   int64  
 1   Order ID       9800 non-null   object 
 2   Order Date     9800 non-null   object 
 3   Ship Date      9800 non-null   object 
 4   Ship Mode      9800 non-null   object 
 5   Customer ID    9800 non-null   object 
 6   Customer Name  9800 non-null   object 
 7   Segment        9800 non-null   object 
 8   Country        9800 non-null   object 
 9   City           9800 non-null   object 
 10  State          9800 non-null   object 
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object 
 13  Product ID     9800 non-null   object 
 14  Category       9800 non-null   object 
 15  Sub-Category   9800 non-null   object 
 16  Product Name   9800 non-null   object 
 17  Sales          9800 non-null   float64
dtypes: float

In [64]:
ss_df.describe()

Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

##### The standard deviation is high showing that the sales difference is huge.

In [77]:
cat_df = ss_df.select_dtypes(include=['category', 'object'])

In [78]:
cat_columns = [i for i in cat_df.columns]

In [79]:
cat_columns

['Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name']

In [82]:
for i in cat_columns:
    print(ss_df[i].value_counts())

Order ID
CA-2018-100111    14
CA-2018-157987    12
CA-2017-165330    11
US-2017-108504    11
CA-2017-105732    10
                  ..
US-2016-110261     1
CA-2016-125710     1
US-2016-137960     1
CA-2016-124975     1
CA-2016-142202     1
Name: count, Length: 4922, dtype: int64
Order Date
05/09/2017    38
10/11/2017    35
02/12/2018    34
01/12/2018    34
02/09/2018    33
              ..
25/02/2017     1
25/10/2017     1
21/02/2015     1
11/09/2015     1
09/05/2016     1
Name: count, Length: 1230, dtype: int64
Ship Date
26/09/2018    34
06/12/2018    32
16/12/2016    31
15/09/2018    30
06/09/2018    30
              ..
10/07/2015     1
29/03/2016     1
14/06/2016     1
10/01/2018     1
13/05/2016     1
Name: count, Length: 1326, dtype: int64
Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64
Customer ID
WB-21850    35
MA-17560    34
PP-18955    34
JL-15835    33
CK-12205    32
            ..
JR-15700     1


##### Data Cleaning

In [86]:
ss_df.drop(['Order ID', 'Row ID', 'Customer ID'], axis=1,  inplace=True)

In [87]:
ss_df.head()

Order Date   Ship Date       Ship Mode    Customer Name    Segment  \
0  08/11/2017  11/11/2017    Second Class      Claire Gute   Consumer   
1  08/11/2017  11/11/2017    Second Class      Claire Gute   Consumer   
2  12/06/2017  16/06/2017    Second Class  Darrin Van Huff  Corporate   
3  11/10/2016  18/10/2016  Standard Class   Sean O'Donnell   Consumer   
4  11/10/2016  18/10/2016  Standard Class   Sean O'Donnell   Consumer   

         Country             City       State  Postal Code Region  \
0  United States        Henderson    Kentucky      42420.0  South   
1  United States        Henderson    Kentucky      42420.0  South   
2  United States      Los Angeles  California      90036.0   West   
3  United States  Fort Lauderdale     Florida      33311.0  South   
4  United States  Fort Lauderdale     Florida      33311.0  South   

        Product ID         Category Sub-Category  \
0  FUR-BO-10001798        Furniture    Bookcases   
1  FUR-CH-10000454        Furniture       Chairs   
2  OFF-LA-10000240  Office Supplies       Labels   
3  FUR-TA-10000577        Furniture       Tables   
4  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  
0                  Bush Somerset Collection Bookcase  261.9600  
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400  
2  Self-Adhesive Address Labels for Typewriters b...   14.6200  
3      Bretford CR4500 Series Slim Rectangular Table  957.5775  
4                     Eldon Fold 'N Roll Cart System   22.3680

In [94]:
ss_df['Order Date'] = pd.to_datetime(ss_df['Order Date'], format="%d/%m/%Y")

In [93]:
ss_df['Ship Date'] = pd.to_datetime(ss_df['Ship Date'], format="%d/%m/%Y")

In [95]:
ss_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Order Date     9800 non-null   datetime64[ns]
 1   Ship Date      9800 non-null   datetime64[ns]
 2   Ship Mode      9800 non-null   object        
 3   Customer Name  9800 non-null   object        
 4   Segment        9800 non-null   object        
 5   Country        9800 non-null   object        
 6   City           9800 non-null   object        
 7   State          9800 non-null   object        
 8   Postal Code    9789 non-null   float64       
 9   Region         9800 non-null   object        
 10  Product ID     9800 non-null   object        
 11  Category       9800 non-null   object        
 12  Sub-Category   9800 non-null   object        
 13  Product Name   9800 non-null   object        
 14  Sales          9800 non-null   float64       
dtypes: datetime64[ns](2),

In [99]:
ss_df.duplicated().sum()

1

In [100]:
ss_df.drop_duplicates(inplace=True)

In [101]:
ss_df.duplicated().sum()

0

In [105]:
ss_df[ss_df['Postal Code'].isnull()]

Order Date  Ship Date       Ship Mode     Customer Name      Segment  \
2234 2018-12-05 2018-12-10  Standard Class      Quincy Jones    Corporate   
5274 2016-11-07 2016-11-09    Second Class  Stewart Visinsky     Consumer   
8798 2017-04-06 2017-04-10  Standard Class   Valerie Mitchum  Home Office   
9146 2017-01-23 2017-01-27  Standard Class  Claudia Bergmann    Corporate   
9147 2017-01-23 2017-01-27  Standard Class  Claudia Bergmann    Corporate   
9148 2017-01-23 2017-01-27  Standard Class  Claudia Bergmann    Corporate   
9386 2018-01-19 2018-01-23  Standard Class     Raymond Messe     Consumer   
9387 2018-01-19 2018-01-23  Standard Class     Raymond Messe     Consumer   
9388 2018-01-19 2018-01-23  Standard Class     Raymond Messe     Consumer   
9389 2018-01-19 2018-01-23  Standard Class     Raymond Messe     Consumer   
9741 2016-11-08 2016-11-12  Standard Class      Quincy Jones    Corporate   

            Country        City    State  Postal Code Region       Product ID  \
2234  United States  Burlington  Vermont          NaN   East  TEC-AC-10001013   
5274  United States  Burlington  Vermont          NaN   East  FUR-CH-10000595   
8798  United States  Burlington  Vermont          NaN   East  TEC-PH-10002555   
9146  United States  Burlington  Vermont          NaN   East  TEC-AC-10002926   
9147  United States  Burlington  Vermont          NaN   East  OFF-AR-10003477   
9148  United States  Burlington  Vermont          NaN   East  OFF-ST-10001526   
9386  United States  Burlington  Vermont          NaN   East  OFF-PA-10000157   
9387  United States  Burlington  Vermont          NaN   East  OFF-PA-10001970   
9388  United States  Burlington  Vermont          NaN   East  OFF-AP-10000828   
9389  United States  Burlington  Vermont          NaN   East  OFF-EN-10001509   
9741  United States  Burlington  Vermont          NaN   East  FUR-BO-10004834   

             Category Sub-Category  \
2234       Technology  Accessories   
5274        Furniture       Chairs   
8798       Technology       Phones   
9146       Technology  Accessories   
9147  Office Supplies          Art   
9148  Office Supplies      Storage   
9386  Office Supplies        Paper   
9387  Office Supplies        Paper   
9388  Office Supplies   Appliances   
9389  Office Supplies    Envelopes   
9741        Furniture    Bookcases   

                                           Product Name    Sales  
2234        Logitech ClearChat Comfort/USB Headset H390   205.03  
5274                    Safco Contoured Stacking Chairs   715.20  
8798                Nortel Meridian M5316 Digital phone  1294.75  
9146              Logitech Wireless Marathon Mouse M705    99.98  
9147                                  4009 Highlighters     8.04  
9148              Iceberg Mobile Mega Data/Printer Cart  1564.29  
9386                                          Xerox 191    79.92  
9387                                         Xerox 1881    12.28  
9388                    Avanti 4.4 Cu. Ft. Refrigerator   542.94  
9389                          Poly String Tie Envelopes     2.04  
9741  Riverside Palais Royal Lawyers Bookcase, Royal...  4404.90

In [106]:
ss_df['Postal Code'] = ss_df['Postal Code'].fillna(0)

In [107]:
ss_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9799 entries, 0 to 9799
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Order Date     9799 non-null   datetime64[ns]
 1   Ship Date      9799 non-null   datetime64[ns]
 2   Ship Mode      9799 non-null   object        
 3   Customer Name  9799 non-null   object        
 4   Segment        9799 non-null   object        
 5   Country        9799 non-null   object        
 6   City           9799 non-null   object        
 7   State          9799 non-null   object        
 8   Postal Code    9799 non-null   float64       
 9   Region         9799 non-null   object        
 10  Product ID     9799 non-null   object        
 11  Category       9799 non-null   object        
 12  Sub-Category   9799 non-null   object        
 13  Product Name   9799 non-null   object        
 14  Sales          9799 non-null   float64       
dtypes: datetime64[ns](2), floa

In [111]:
ss_df.isna().sum()

Order Date       0
Ship Date        0
Ship Mode        0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64